spring.application.name: zipkin-server
server.port: 9411

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
# For deployment in Docker containers
spring:
  profiles: docker

spring.rabbitmq.host: rabbitmq
